# Generated by Django 3.2.13 on 2022-07-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_manage',
        ),
    ]
