# Generated by Django 3.1.2 on 2022-10-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='css',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='html',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
