# Generated by Django 4.0.6 on 2022-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_forget_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.TextField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
