# Generated by Django 3.1.2 on 2022-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20221010_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bootstrap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='java',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='javascripts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='jquery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='python',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='react',
            field=models.BooleanField(default=False),
        ),
    ]
