# Generated by Django 3.1.2 on 2022-10-10 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20221010_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bootstrap',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='css',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='html',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='java',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='javascripts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jquery',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='python',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='react',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.BooleanField(default=False)),
                ('html', models.BooleanField(default=False)),
                ('jquery', models.BooleanField(default=False)),
                ('javascripts', models.BooleanField(default=False)),
                ('bootstrap', models.BooleanField(default=False)),
                ('react', models.BooleanField(default=False)),
                ('java', models.BooleanField(default=False)),
                ('python', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
