# Generated by Django 3.1.2 on 2022-10-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0007_auto_20221011_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catagory Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ecommerce/catagory-image', verbose_name='Catagory Image')),
                ('catagory_slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='Cat slugify')),
            ],
        ),
        migrations.CreateModel(
            name='Add_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('product_description', models.TextField(verbose_name='Short Description')),
                ('product_image', models.ImageField(default='ecommerce/default.jpg', upload_to='ecommerce/product-image', verbose_name='Product Image')),
                ('product_price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('product_discount', models.FloatField(blank=True, null=True, verbose_name='Discount')),
                ('additional_image1', models.ImageField(blank=True, null=True, upload_to='ecommerce/additional-image', verbose_name='Additional Image1')),
                ('additional_image2', models.ImageField(blank=True, null=True, upload_to='ecommerce/additional-image', verbose_name='Additional Image2')),
                ('additional_image3', models.ImageField(blank=True, null=True, upload_to='ecommerce/additional-image', verbose_name='Additional Image3')),
                ('feedback_average', models.PositiveIntegerField(blank=True, null=True, verbose_name='Feedback Average')),
                ('feedback_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Feedback Number')),
                ('product_width', models.FloatField(blank=True, null=True, verbose_name='Width')),
                ('product_height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('product_weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('product_pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pieces/set')),
                ('product_available', models.PositiveIntegerField(blank=True, null=True, verbose_name='available')),
                ('product_is_sale', models.BooleanField(default=False, verbose_name='Sale')),
                ('product_is_active', models.BooleanField(default=False, verbose_name='Product active')),
                ('product_is_deleted', models.BooleanField(default=False, verbose_name='Product Deleted')),
                ('product_slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True, verbose_name='Slugify')),
                ('date_upload', models.DateField(auto_now_add=True, null=True, verbose_name='-Date')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='-Update')),
                ('product_catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product_catagory', verbose_name='Catagory')),
                ('product_vender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.profile', verbose_name='product_vender')),
            ],
        ),
    ]
