# Generated by Django 3.1.2 on 2022-10-19 05:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20221011_0420'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('clint_comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment')),
                ('active', models.BooleanField(default=True)),
                ('rating_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('rating_update', models.DateTimeField(auto_now=True)),
                ('clint_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='management.profile', verbose_name='Clint')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.add_product', verbose_name='Add_product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vender', to='management.profile', verbose_name='Supplier')),
            ],
        ),
    ]
